// Herbs and fruits of the Bible. Verses are quoted from the King James Version (public domain).
// link: { herb: id } or { fruit: id } when the plant has its own page on the site.

const BIBLE_INTRO = { text: "And God said, Behold, I have given you every herb bearing seed, which is upon the face of all the earth, and every tree, in the which is the fruit of a tree yielding seed; to you it shall be for meat.", ref: "Genesis 1:29" };

const BIBLE_PLANTS = [
  { name: "Hyssop", ref: "Psalm 51:7", verse: "Purge me with hyssop, and I shall be clean: wash me, and I shall be whiter than snow.", note: "Hyssop was used in cleansing rituals and to sprinkle the blood of the Passover lamb. The biblical plant was likely a relative such as Syrian oregano.", link: { herb: "hyssop" } },
  { name: "Mustard Seed", ref: "Matthew 13:31", verse: "The kingdom of heaven is like to a grain of mustard seed, which a man took, and sowed in his field:", note: "Jesus used the tiny mustard seed, which grows into a large plant, as a picture of faith and the growing kingdom.", link: { herb: "mustard" } },
  { name: "Mint, Anise & Cumin", ref: "Matthew 23:23", verse: "for ye pay tithe of mint and anise and cummin, and have omitted the weightier matters of the law, judgment, mercy, and faith:", note: "These everyday garden herbs were so valued that people tithed them. The 'anise' here is generally understood to be dill.", link: { herb: "peppermint" }, extra: [{ herb: "dill" }, { herb: "cumin" }] },
  { name: "Coriander", ref: "Exodus 16:31", verse: "and it was like coriander seed, white; and the taste of it was like wafers made with honey.", note: "Manna, the bread from heaven in the wilderness, was described as looking like coriander seed.", link: { herb: "coriander" } },
  { name: "Garlic", ref: "Numbers 11:5", verse: "We remember the fish, which we did eat in Egypt freely; the cucumbers, and the melons, and the leeks, and the onions, and the garlick:", note: "The Israelites remembered the garlic, cucumbers and melons of Egypt during their wilderness journey.", link: { herb: "garlic" }, extra: [{ fruit: "cucumber" }, { fruit: "watermelon" }] },
  { name: "Saffron & Cinnamon", ref: "Song of Solomon 4:14", verse: "Spikenard and saffron; calamus and cinnamon, with all trees of frankincense; myrrh and aloes, with all the chief spices:", note: "The Song of Solomon describes a garden of the finest spices as a picture of beauty and love.", link: { herb: "saffron" }, extra: [{ herb: "cinnamon" }] },
  { name: "Sweet Cinnamon", ref: "Exodus 30:23", verse: "Take thou also unto thee principal spices, of pure myrrh five hundred shekels, and of sweet cinnamon half so much,", note: "Cinnamon was an ingredient in the holy anointing oil of the tabernacle.", link: { herb: "cinnamon" } },
  { name: "Frankincense & Myrrh", ref: "Matthew 2:11", verse: "and when they had opened their treasures, they presented unto him gifts; gold, and frankincense, and myrrh.", note: "Precious tree resins brought by the wise men to the infant Jesus. They are not featured as herbs on this site." },
  { name: "Aloes", ref: "John 19:39", verse: "and brought a mixture of myrrh and aloes, about an hundred pound weight.", note: "Nicodemus brought myrrh and aloes to prepare Jesus' body. Biblical 'aloes' may have been fragrant aloeswood rather than aloe vera.", link: { herb: "aloe-vera" } },
  { name: "Bitter Herbs", ref: "Exodus 12:8", verse: "And they shall eat the flesh in that night, roast with fire, and unleavened bread; and with bitter herbs they shall eat it.", note: "Bitter herbs at Passover recall the bitterness of slavery. Chicory, endive and dandelion are among the traditional bitter herbs.", link: { herb: "chicory" }, extra: [{ herb: "dandelion" }] },
  { name: "Every Herb", ref: "Luke 11:42", verse: "for ye tithe mint and rue and all manner of herbs, and pass over judgment and the love of God:", note: "Jesus reminds us that faithful giving matters, but justice and the love of God matter most.", link: { herb: "spearmint" } },
  { name: "Balm of Gilead", ref: "Jeremiah 8:22", verse: "Is there no balm in Gilead; is there no physician there?", note: "Gilead was famous for a healing balm, probably a resin. It became a symbol of spiritual healing." },
  { name: "Olive", ref: "Genesis 8:11", verse: "And the dove came in to him in the evening; and, lo, in her mouth was an olive leaf pluckt off:", note: "The olive leaf brought by the dove after the flood became a lasting symbol of peace and new beginnings.", link: { fruit: "olive" }, extra: [{ herb: "olive-leaf" }] },
  { name: "The Green Olive Tree", ref: "Psalm 52:8", verse: "But I am like a green olive tree in the house of God: I trust in the mercy of God for ever and ever.", note: "Olive trees live for centuries, a picture of a life rooted in God.", link: { fruit: "olive" } },
  { name: "Fig", ref: "Isaiah 38:21", verse: "For Isaiah had said, Let them take a lump of figs, and lay it for a plaister upon the boil, and he shall recover.", note: "King Hezekiah's boil was treated with a poultice of figs — one of the earliest recorded uses of a fruit as medicine.", link: { fruit: "fig" } },
  { name: "Pomegranate", ref: "Exodus 28:34", verse: "A golden bell and a pomegranate, a golden bell and a pomegranate, upon the hem of the robe round about.", note: "Pomegranates decorated the high priest's robe and the pillars of Solomon's temple.", link: { fruit: "pomegranate" } },
  { name: "The Vine", ref: "John 15:5", verse: "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit:", note: "Jesus used the grapevine to describe our connection to Him.", link: { fruit: "grape" }, extra: [{ fruit: "raisin" }] },
  { name: "Date Palm", ref: "Psalm 92:12", verse: "The righteous shall flourish like the palm tree:", note: "The date palm, tall and fruitful in the desert, is a picture of a flourishing life.", link: { fruit: "date" } },
  { name: "Apple", ref: "Proverbs 25:11", verse: "A word fitly spoken is like apples of gold in pictures of silver.", note: "Kind and timely words are as beautiful as golden fruit. (The Hebrew word may also refer to apricots or citrons.)", link: { fruit: "apple" }, extra: [{ fruit: "apricot" }, { fruit: "citron" }] },
  { name: "The Land of Plenty", ref: "Deuteronomy 8:8", verse: "A land of wheat, and barley, and vines, and fig trees, and pomegranates; a land of oil olive, and honey;", note: "The seven foods of the Promised Land describe God's abundant provision.", link: { fruit: "pomegranate" }, extra: [{ fruit: "fig" }, { fruit: "grape" }, { fruit: "olive" }, { fruit: "date" }] },
  { name: "Leaves for Healing", ref: "Ezekiel 47:12", verse: "and the fruit thereof shall be for meat, and the leaf thereof for medicine.", note: "Ezekiel's vision of the river from the temple describes trees whose fruit feeds and whose leaves heal." }
];
