// Headline doses for each herb, per person (adults 100 lb / 45 kg and over).
//
// cap:  [min mg, max mg, what's in the capsule, how often]  — or a string explaining why there's no capsule dose.
// herb: [min g, max g, how to take the herb by itself, how often] — min may be a string for non-weight amounts.

const CAPS = {
  chamomile: { cap: [220, 500, "Chamomile extract", "1–3 times a day"], herb: [2, 3, "Dried flowers steeped as tea (per cup)", "3–4 times a day"] },
  peppermint: { cap: [180, 200, "Enteric-coated peppermint oil", "3 times a day, before meals"], herb: [1.5, 3, "Dried leaf steeped as tea (per cup)", "3 times a day"] },
  spearmint: { cap: [400, 800, "Powdered spearmint leaf", "2 times a day"], herb: [1, 2, "Dried leaf steeped as tea (per cup)", "2 times a day"] },
  ginger: { cap: [250, 500, "Powdered ginger root", "2–4 times a day (max 4,000 mg a day)"], herb: [0.5, 1, "Dried ground ginger in water, food or tea", "2–3 times a day"] },
  turmeric: { cap: [500, 500, "Curcumin extract with black pepper (piperine)", "1–2 times a day with food"], herb: [0.5, 1, "Ground turmeric in food or warm milk", "2–3 times a day"] },
  lavender: { cap: [80, 80, "Lavender oil capsule (Silexan)", "Once a day"], herb: [1, 2, "Dried flowers steeped as tea (per cup)", "Up to 3 times a day"] },
  rosemary: { cap: [500, 1000, "Powdered rosemary leaf", "2 times a day"], herb: [1, 2, "Dried leaf steeped as tea (per cup)", "Up to 3 times a day"] },
  thyme: { cap: [500, 1000, "Powdered thyme herb", "2–3 times a day"], herb: [1, 2, "Dried herb steeped as tea (per cup)", "3–4 times a day"] },
  sage: { cap: [280, 600, "Sage leaf extract", "1–2 times a day (max 4 weeks)"], herb: [1, 2, "Dried leaf steeped as tea (per cup)", "Up to 3 times a day"] },
  oregano: { cap: [450, 500, "Powdered oregano leaf", "1–2 times a day"], herb: [1, 2, "Dried leaf steeped as tea (per cup)", "Up to 3 times a day"] },
  basil: { cap: [500, 500, "Powdered basil leaf", "1–2 times a day"], herb: [1, 2, "Dried leaf steeped as tea (per cup)", "2–3 times a day"] },
  "holy-basil": { cap: [300, 500, "Holy basil (tulsi) leaf extract", "2 times a day"], herb: [2, 3, "Dried leaf steeped as tea (per cup)", "1–2 times a day"] },
  parsley: { cap: [450, 900, "Powdered parsley leaf", "1–2 times a day"], herb: [2, 2, "Dried leaf steeped as tea (per cup)", "Up to 3 times a day"] },
  coriander: { cap: [500, 1000, "Powdered coriander seed", "2 times a day"], herb: [1, 1, "Crushed seed steeped as tea (per cup)", "Up to 3 times a day"] },
  dill: { cap: "Not commonly sold as capsules — use the seed as tea.", herb: [1, 3, "Crushed seed steeped as tea (per cup)", "Up to 3 times a day"] },
  fennel: { cap: [500, 1000, "Powdered fennel seed", "2–3 times a day"], herb: [1.5, 2.5, "Crushed seed steeped as tea (per cup)", "3 times a day"] },
  "lemon-balm": { cap: [300, 600, "Lemon balm extract", "1–2 times a day"], herb: [1.5, 4.5, "Dried leaf steeped as tea (per cup)", "2–3 times a day"] },
  lemongrass: { cap: "Not commonly sold as capsules — use the stalk as tea.", herb: [2, 3, "Fresh or dried stalk steeped as tea (per cup)", "Up to 3 times a day"] },
  "lemon-verbena": { cap: [400, 400, "Lemon verbena extract", "Once a day"], herb: [1.5, 3, "Dried leaf steeped as tea (per cup)", "Up to 3 times a day"] },
  garlic: { cap: [600, 1200, "Aged garlic extract", "Once a day with food"], herb: [3, 4, "1 fresh clove, crushed, rested 10 minutes", "Once a day"] },
  cinnamon: { cap: [500, 1000, "Ceylon cinnamon powder", "1–2 times a day (cassia: max 1,000 mg a day)"], herb: [0.5, 1.3, "Ground Ceylon cinnamon (¼–½ teaspoon)", "1–2 times a day"] },
  clove: { cap: "Not recommended as capsules — use whole cloves in tea or food.", herb: [0.1, 0.3, "2–4 whole cloves in tea or cooking", "1–3 times a day"] },
  cardamom: { cap: [500, 1500, "Powdered cardamom", "2 times a day"], herb: [0.5, 1.5, "Ground cardamom in food or drinks", "1–2 times a day"] },
  nutmeg: { cap: "Do not take nutmeg as capsules — concentrated nutmeg can be poisonous.", herb: [0.1, 0.5, "Freshly grated nutmeg — a pinch (never more than 500 mg a day)", "Once a day"] },
  "black-pepper": { cap: [5, 20, "Piperine (black pepper extract), only alongside turmeric/curcumin", "With each curcumin dose"], herb: [0.5, 1, "Ground pepper in food", "With meals"] },
  cayenne: { cap: [450, 500, "Powdered cayenne", "1–3 times a day with meals"], herb: [0.25, 1, "Ground cayenne in food", "With meals"] },
  cumin: { cap: [500, 1000, "Powdered cumin seed", "2–3 times a day with meals"], herb: [1, 3, "Ground cumin in food", "Daily, split among meals"] },
  fenugreek: { cap: [1000, 2000, "Powdered fenugreek seed (usually 2–3 capsules of 500–610 mg)", "3 times a day"], herb: [1, 2, "Seed powder or soaked seeds", "3 times a day"] },
  anise: { cap: "Not commonly sold as capsules — use the seed as tea.", herb: [1, 1, "Crushed seed steeped as tea (per cup)", "Up to 3 times a day"] },
  "star-anise": { cap: "Not sold as capsules — use whole stars in tea or broth.", herb: [1, 1, "1 whole star in tea or broth", "Up to 3 times a day"] },
  licorice: { cap: [380, 760, "DGL licorice (chewable)", "Before meals, 2–3 times a day"], herb: [1, 2, "Dried root simmered as tea (per cup) — max 4–6 weeks", "Up to 3 times a day"] },
  "marshmallow-root": { cap: [1000, 2000, "Powdered marshmallow root (with a full glass of water)", "3 times a day"], herb: [2, 5, "Root soaked in cool water 4–8 hours (per cup)", "Up to 3 times a day"] },
  "slippery-elm": { cap: [800, 1500, "Powdered slippery elm bark (with a full glass of water)", "3 times a day"], herb: [1.5, 3, "Powder stirred into warm water or oatmeal", "Up to 3 times a day"] },
  echinacea: { cap: [300, 500, "Echinacea extract", "3 times a day, up to 10 days"], herb: [1, 2, "Dried herb or root steeped as tea (per cup)", "3 times a day"] },
  elderberry: { cap: [300, 300, "Elderberry extract", "2–3 times a day"], herb: ["1 tablespoon (15 ml) of cooked syrup", null, "Homemade syrup — never raw berries", "Once a day, or up to 4 times a day when sick"] },
  elderflower: { cap: "Not commonly sold as capsules — use the flowers as tea.", herb: [3, 4, "Dried flowers steeped as tea (per cup)", "3 times a day, hot"] },
  calendula: { cap: "Not commonly taken as capsules — mainly used on the skin.", herb: [1, 2, "Dried petals steeped as tea or mouth rinse (per cup)", "Up to 3 times a day"] },
  rose: { cap: "Not commonly sold as capsules — use the petals as tea.", herb: [1, 2, "Dried petals steeped as tea (per cup)", "1–3 times a day"] },
  hibiscus: { cap: [250, 500, "Hibiscus extract", "1–2 times a day"], herb: [1.5, 2.5, "Dried calyces steeped as tea (per cup)", "2–3 times a day"] },
  "aloe-vera": { cap: "Not recommended by mouth — aloe is for use on the skin.", herb: null },
  dandelion: { cap: [500, 1000, "Powdered dandelion root", "2–3 times a day"], herb: [3, 4, "Dried root simmered as tea (per cup)", "3 times a day"] },
  burdock: { cap: [500, 1000, "Powdered burdock root", "2–3 times a day"], herb: [1, 2, "Dried root simmered as tea (per cup)", "3 times a day"] },
  nettle: { cap: [500, 1000, "Powdered nettle leaf", "2–3 times a day"], herb: [2, 4, "Dried leaf steeped as tea (per cup)", "3 times a day"] },
  "red-clover": { cap: [40, 80, "Red clover isoflavone extract", "Once a day"], herb: [1, 2, "Dried blossoms steeped as tea (per cup)", "Up to 3 times a day"] },
  "milk-thistle": { cap: [140, 175, "Milk thistle extract (70–80% silymarin)", "2–3 times a day"], herb: [3, 5, "Freshly ground seed in food or tea", "3 times a day"] },
  hawthorn: { cap: [160, 450, "Hawthorn leaf & flower extract", "2 times a day"], herb: [1, 1.5, "Dried berries or leaf & flower as tea (per cup)", "3–4 times a day"] },
  ginkgo: { cap: [60, 120, "Standardized ginkgo leaf extract (EGb 761)", "2 times a day"], herb: ["Not recommended", null, "Homemade leaf tea is too weak and inconsistent — use the extract", ""] },
  ginseng: { cap: [200, 400, "Standardized ginseng root extract", "Once a day, for up to 3 months"], herb: [1, 2, "Dried root, sliced and simmered as tea", "Once a day"] },
  ashwagandha: { cap: [300, 300, "Ashwagandha root extract", "1–2 times a day"], herb: [1, 3, "Root powder in warm milk", "1–2 times a day"] },
  rhodiola: { cap: [200, 600, "Rhodiola root extract (3% rosavins, 1% salidroside)", "Once a day, in the morning"], herb: ["Usually taken as extract", null, "Rhodiola root is rarely used on its own — use the capsule", ""] },
  valerian: { cap: [300, 600, "Valerian root extract", "Once, 30–120 minutes before bed"], herb: [2, 3, "Dried root steeped as tea (per cup)", "Once, 30–60 minutes before bed"] },
  passionflower: { cap: [400, 500, "Powdered passionflower herb", "1–3 times a day"], herb: [1, 2, "Dried herb steeped as tea (per cup)", "2–3 times a day, or once at bedtime"] },
  skullcap: { cap: [400, 500, "Powdered skullcap herb (from a reputable supplier)", "1–3 times a day"], herb: [1, 2, "Dried herb steeped as tea (per cup)", "3 times a day"] },
  hops: { cap: [300, 500, "Hops strobile powder (often combined with valerian)", "Once, at bedtime"], herb: [0.5, 1, "Dried strobiles steeped as tea", "Once, at bedtime"] },
  catnip: { cap: [400, 500, "Powdered catnip herb", "1–3 times a day"], herb: [1, 2, "Dried leaf steeped as tea (per cup)", "Up to 3 times a day"] },
  linden: { cap: "Not commonly sold as capsules — use the flowers as tea.", herb: [2, 4, "Dried flowers steeped as tea (per cup)", "1–3 times a day"] },
  "oat-straw": { cap: [800, 1600, "Green oat (Avena sativa) extract", "Once a day"], herb: [3, 3, "Dried oat straw steeped as tea (per cup)", "Up to 3 times a day"] },
  horsetail: { cap: [300, 300, "Horsetail extract (thiaminase-free)", "3 times a day, up to 6 weeks"], herb: [2, 4, "Dried herb steeped as tea (per cup)", "2–3 times a day"] },
  yarrow: { cap: "Not commonly sold as capsules — use the herb as tea.", herb: [1.5, 2, "Dried herb steeped as tea (per cup)", "3 times a day"] },
  plantain: { cap: "Not commonly sold as capsules — use the leaf as tea or on the skin.", herb: [1.5, 2, "Dried leaf steeped as tea (per cup)", "3–4 times a day"] },
  mullein: { cap: "Not commonly sold as capsules — use the leaf as tea.", herb: [1.5, 2, "Dried leaf steeped as tea, strained through cloth (per cup)", "3–4 times a day"] },
  hyssop: { cap: "Not commonly sold as capsules — use the herb as tea.", herb: [1, 2, "Dried herb steeped as tea (per cup)", "Up to 3 times a day"] },
  horehound: { cap: "Usually taken as lozenges or tea rather than capsules.", herb: [1, 2, "Dried herb steeped as tea (per cup)", "3 times a day"] },
  eucalyptus: { cap: [200, 200, "Enteric-coated cineole (eucalyptol) capsules", "3 times a day"], herb: [1.5, 2, "Dried leaf steeped as tea (per cup)", "Up to 3 times a day"] },
  "tea-tree": { cap: "Never swallow tea tree — it is for use on the skin only.", herb: null },
  "witch-hazel": { cap: "Not taken by mouth — witch hazel is for use on the skin.", herb: null },
  arnica: { cap: "Never swallow arnica — it is poisonous by mouth (except highly diluted homeopathic pills).", herb: null },
  "st-johns-wort": { cap: [300, 300, "Standardized extract (0.3% hypericin) — only with medical guidance", "3 times a day"], herb: [2, 4, "Dried herb as tea, per day — only with medical guidance", "Once a day, or split"] },
  "saw-palmetto": { cap: [160, 320, "Saw palmetto berry extract", "160 mg twice a day, or 320 mg once"], herb: [1, 2, "Whole dried berries, ground", "Once a day"] },
  chasteberry: { cap: [20, 40, "Chasteberry fruit extract", "Once a day, in the morning"], herb: [0.03, 0.04, "Crushed dried berries", "Once a day, in the morning"] },
  "raspberry-leaf": { cap: [400, 1200, "Raspberry leaf (in pregnancy only with your midwife)", "2 times a day"], herb: [1.5, 2.5, "Dried leaf steeped as tea (per cup)", "Up to 3 times a day"] },
  moringa: { cap: [800, 2000, "Moringa leaf powder (usually 2–4 capsules)", "1–2 times a day"], herb: [1, 3, "Leaf powder in food or smoothies", "1–2 times a day"] },
  "green-tea": { cap: [250, 500, "Green tea extract (keep EGCG under 800 mg a day)", "Once a day with food"], herb: [2, 3, "Dried leaf steeped as tea (per cup)", "2–4 times a day"] },
  rooibos: { cap: "Not commonly sold as capsules — enjoy it as tea.", herb: [2, 3, "Dried leaf steeped as tea (per cup)", "Up to 6 times a day"] },
  "yerba-mate": { cap: [500, 1000, "Yerba mate extract (contains caffeine)", "1–2 times a day, before mid-afternoon"], herb: [3, 5, "Dried leaf steeped as tea (per cup)", "1–3 times a day"] },
  "gotu-kola": { cap: [30, 60, "Gotu kola extract (TTFCA)", "2 times a day, up to 6 weeks"], herb: [0.6, 2, "Dried leaf steeped as tea (per cup)", "3 times a day"] },
  bacopa: { cap: [300, 450, "Bacopa extract (50% bacosides)", "Once a day with food"], herb: ["Usually taken as extract", null, "Bacopa is bitter and rarely taken on its own — use the capsule", ""] },
  schisandra: { cap: [500, 1000, "Schisandra berry extract", "Once a day"], herb: [1.5, 3, "Dried berries steeped as tea (per cup)", "1–2 times a day"] },
  astragalus: { cap: [250, 500, "Astragalus root extract", "2–3 times a day"], herb: [3, 10, "Sliced root simmered in soup or tea", "Once a day"] },
  reishi: { cap: [1000, 1500, "Reishi mushroom extract", "Once a day"], herb: [1.5, 3, "Dried slices simmered 1–2 hours as tea", "1–3 times a day"] },
  "olive-leaf": { cap: [500, 500, "Olive leaf extract", "2 times a day"], herb: [2, 3, "Dried leaf steeped as tea (per cup)", "1–3 times a day"] },
  bilberry: { cap: [80, 160, "Bilberry extract (25% anthocyanosides)", "2 times a day"], herb: [20, 60, "Fresh or frozen berries", "Once a day"] },
  cranberry: { cap: [500, 500, "Cranberry extract (36 mg PACs)", "1–2 times a day"], herb: ["1 cup (240–300 ml) unsweetened juice", null, "Unsweetened cranberry juice", "Once a day"] },
  marjoram: { cap: "Not commonly sold as capsules — use the leaf as tea.", herb: [1, 2, "Dried leaf steeped as tea (per cup)", "2 times a day"] },
  tarragon: { cap: "Not commonly sold as capsules — use in cooking.", herb: [0.5, 2, "Fresh or dried leaf in food", "With meals"] },
  "bay-laurel": { cap: [1000, 3000, "Ground bay leaf", "Once a day"], herb: ["1–2 whole leaves", null, "Whole leaves in cooking — remove before eating", "Per dish"] },
  juniper: { cap: "Not recommended as capsules — use berries short-term in tea or food.", herb: [1, 2, "Crushed dried berries steeped as tea (per cup) — max 4 weeks", "Up to 3 times a day"] },
  chicory: { cap: "Usually taken as roasted root or inulin powder rather than capsules.", herb: [2, 4, "Roasted root brewed like coffee (per cup)", "1–3 times a day"] },
  lovage: { cap: "Not commonly sold as capsules — use the root as tea.", herb: [1.5, 3, "Dried root steeped as tea (per cup)", "2–3 times a day"] },
  caraway: { cap: [140, 140, "Caraway oil 50 mg + peppermint oil 90 mg (combined capsule)", "2 times a day"], herb: [1, 2, "Crushed seed steeped as tea (per cup)", "3 times a day"] },
  mustard: { cap: "Not taken as capsules — use in food.", herb: [1, 5, "Mustard seed or prepared mustard in food", "With meals"] },
  saffron: { cap: [30, 30, "Saffron extract (or 15 mg twice a day)", "Once a day"], herb: [0.03, 0.1, "Saffron threads soaked in warm water or milk", "Once a day"] },
  vanilla: { cap: "Not taken as capsules — use in food.", herb: ["1–2 teaspoons (5–10 ml) pure extract", null, "Pure vanilla extract in food", "Per recipe"] },
  feverfew: { cap: [50, 150, "Feverfew leaf (0.2–0.4% parthenolide)", "Once a day, for at least 4 weeks"], herb: ["Capsules preferred", null, "Chewing fresh leaves can cause mouth sores — use the capsule", ""] },
  meadowsweet: { cap: "Not commonly sold as capsules — use the flowers as tea.", herb: [1, 2, "Dried flowers steeped as tea (per cup)", "Up to 3 times a day"] },
  chickweed: { cap: "Not commonly sold as capsules — eat fresh or use as tea or salve.", herb: [1, 2, "Dried herb steeped as tea (per cup)", "Up to 3 times a day"] },
  violet: { cap: "Not commonly sold as capsules — use the leaves and flowers as tea.", herb: [1, 2, "Dried leaf and flower steeped as tea (per cup)", "Up to 3 times a day"] },
  "rose-hips": { cap: [2250, 2500, "Rose hip powder (usually 3–4 capsules)", "2 times a day"], herb: [2.5, 5, "Rose hip powder in food or water", "1–2 times a day"] },
  "black-seed": { cap: [500, 1500, "Black seed oil softgels", "1–2 times a day"], herb: [1, 2, "Ground seeds in food", "1–2 times a day"] },
  neem: { cap: "Never swallow neem oil. Neem leaf capsules should only be used with medical guidance.", herb: null },
  "tongkat-ali": { cap: [200, 400, "Standardized root water extract", "Once a day, in the morning"], herb: ["Usually taken as extract", null, "The raw root is very bitter and hard to dose — use a tested extract", ""] },
  "shilajit": { cap: [250, 250, "Purified shilajit extract", "Twice a day, with food"], herb: [0.3, 0.5, "Purified resin (about a pea-sized piece) dissolved in warm water", "Once a day"] },
  "mucuna": { cap: [300, 500, "Standardized seed extract (15% L-dopa)", "1–2 times a day, with food"], herb: [2.5, 5, "Powdered seeds stirred into milk or a smoothie", "Once a day, with food"] },
  "tribulus": { cap: [250, 750, "Standardized fruit extract", "1–2 times a day, with food"], herb: [3, 6, "Dried fruit simmered as tea (Chinese medicine style)", "Once a day"] },
  "maca": { cap: [1500, 3000, "Gelatinized maca root", "Once a day (usually 3–6 capsules)"], herb: [3, 5, "Gelatinized powder in smoothies, oatmeal or coffee", "Once a day"] },
  "horny-goat-weed": { cap: [250, 500, "Extract standardized to 10–20% icariin", "Once or twice a day"], herb: [3, 6, "Dried leaf simmered as tea", "Once a day"] },
  "cordyceps": { cap: [1000, 3000, "Cordyceps extract (Cs-4 or C. militaris)", "Once a day, or split morning and midday"], herb: [3, 6, "Dried fruiting bodies simmered in soup or tea", "Once a day"] }
};
